/* SPDX-FileCopyrightText: 2026 Core Devices LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#pragma once

#define FRAMEBUFFER_DAMAGE_TILE_SIZE 16
#define FRAMEBUFFER_DAMAGE_TILE_COLUMNS \
  ((DISP_COLS + FRAMEBUFFER_DAMAGE_TILE_SIZE - 1) / FRAMEBUFFER_DAMAGE_TILE_SIZE)
#define FRAMEBUFFER_DAMAGE_TILE_ROWS \
  ((DISP_ROWS + FRAMEBUFFER_DAMAGE_TILE_SIZE - 1) / FRAMEBUFFER_DAMAGE_TILE_SIZE)
#define FRAMEBUFFER_DAMAGE_TILE_WORDS ((FRAMEBUFFER_DAMAGE_TILE_ROWS + 31) / 32)
